### ISSUE TITLE
Generate CSS variables

### ISSUE THREAD

**Issue by ryangittings** [hankchizljaw/goron#2]
Hey hey,

It'd be awesome if we could specify whether the property should be generated as a class, CSS variable or both, on a per property basis? :)

**Comment by Andy-set-studio** [comment]
Yeh you can do that already! 

You add an item to the config like this:

```js
    'my-custom-prop': {
      items: {
        foo: '100px',
        bar: '200px'
      },
      output: 'standard',
      property: '--a-custom-property'
    }
```

Then you get: 

```css
.my-custom-prop-foo {
  --a-custom-property: 100px;
}

.my-custom-prop-bar {
  --a-custom-property: 200px;
}
```
